obj-y		+= test_driver.o

#KERNELDIR ?=/lib/modules/$(shell uname -r)/build
##KERNELDIR ?=$(HOME)/disk2/cht_r2/out/target/product/r2_cht_mrd/obj/kernel/lib/modules/3.14.79-x86_64-gb1e6894/build/
##Documentation/kbuild/kbuild.txt

#module:
	#$(MAKE) -C $(KERNELDIR) M=$(shell pwd) modules
	#rm -rf *.c~
	#rm -rf *.mod*
	#rm -rf *.o
	#rm -rf modules.order
	#rm -rf Module.symvers

#clean:
	#rm -rf *.ko *.o *.mod* modules* Mo* .*.cmd .tmp_versions
	#make -C $(KERNELDIR) M=`pwd` clean

#obj-m=test_driver.o
